# Generated by Django 5.2.12 on 2026-04-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_button', models.CharField(max_length=100)),
                ('demo_button', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfoliodata',
            options={'verbose_name': 'Portfolio Data', 'verbose_name_plural': 'Portfolio Data'},
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='CtrlS.navbar')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('resources', 'Resources'), ('company', 'Company')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=200)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='CtrlS.navbar')),
            ],
        ),
    ]
