# Generated by Django 5.2.12 on 2026-04-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0002_navbar_alter_portfoliodata_options_menuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField()),
                ('description', models.TextField()),
                ('copyright', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfoliodata',
            options={},
        ),
        migrations.CreateModel(
            name='DemoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_label', models.CharField(max_length=100)),
                ('email_label', models.CharField(max_length=100)),
                ('organization_label', models.CharField(max_length=100)),
                ('source_label', models.CharField(max_length=100)),
                ('submit_text', models.CharField(max_length=100)),
                ('demo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='CtrlS.demo')),
            ],
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CtrlS.footersection')),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='CtrlS.visibility')),
            ],
        ),
    ]
