# Generated by Django 5.2.12 on 2026-04-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0003_demo_footer_footersection_hero_infrastructurecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='footer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='CtrlS.footer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='type',
            field=models.CharField(choices=[('resources', 'Resources'), ('platform', 'Platform'), ('company', 'Company'), ('get_started', 'Get Started')], max_length=20),
        ),
    ]
