# Generated by Django 5.2.12 on 2026-04-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0004_footersection_footer_alter_dropdownitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CtrlS.demo')),
            ],
        ),
    ]
