# Generated by Django 5.2.12 on 2026-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
