# Generated by Django 5.2.12 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0012_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(),
        ),
    ]
