# Generated by Django 5.2.12 on 2026-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0013_alter_card_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dropdownitem',
            name='navbar',
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
