# Generated by Django 5.2.12 on 2026-04-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0014_remove_dropdownitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='navbar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='CtrlS.navbar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='type',
            field=models.CharField(choices=[('resources', 'Resources'), ('platform', 'Platform'), ('company', 'Company'), ('get_started', 'Get Started')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
