# Generated by Django 6.0.4 on 2026-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0015_dropdownitem_description_dropdownitem_navbar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownitem',
            name='type',
            field=models.CharField(choices=[('services', 'Services'), ('resources', 'Resources'), ('platform', 'Platform'), ('company', 'Company'), ('get_started', 'Get Started')], max_length=20),
        ),
    ]
