# Generated by Django 6.0.4 on 2026-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0017_alter_card_description_alter_card_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
