# Generated by Django 6.0.4 on 2026-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0018_alter_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
