# Generated by Django 6.0.4 on 2026-04-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0020_card_created_at_card_image_card_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_content', models.TextField(blank=True, null=True)),
                ('sidebar_items', models.JSONField(blank=True, default=list)),
                ('demo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('demo_description', models.TextField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='CtrlS.card')),
            ],
        ),
    ]
