# Generated by Django 6.0.4 on 2026-04-23 09:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0021_blogcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='file',
        ),
        migrations.AddField(
            model_name='card',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='main_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
