# Generated by Django 6.0.4 on 2026-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0023_rename_name_contact_first_name_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
