# Generated by Django 6.0.4 on 2026-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0024_alter_contact_inquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
