# Generated by Django 6.0.4 on 2026-05-22 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0027_demobooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobooking',
            name='booking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
