# Generated by Django 6.0.4 on 2026-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CtrlS', '0028_demobooking_booking_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='deployment_type',
            field=models.CharField(blank=True, choices=[('multi_cloud', 'Multi-Cloud'), ('on_premise', 'On-Premise'), ('private_cloud', 'Private Cloud'), ('single_cloud', 'Single Cloud')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='estimated_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('event', 'Event / Conference'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='plan_interest',
            field=models.CharField(blank=True, choices=[('free', 'Free Trial'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='segment',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('enterprise', 'Enterprise'), ('datacenter', 'Data Center')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('trial', 'Trial Active'), ('engaged', 'Engaged'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
